/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Addresses {
  address_id: Generated<number>;
  city: string;
  is_default: number;
  state: string;
  street_address: string;
  user_id: number;
  zip_code: string;
}

export interface ItemModifiers {
  combo_id: Generated<number>;
  display_order: number;
  is_active: number;
  is_available: number;
  item_id: number | null;
  modifier_id: number | null;
}

export interface ItemOptionPrices {
  combo_id: Generated<number>;
  is_active: number;
  is_available: number;
  item_id: number;
  option_id: number;
  price: number;
}

export interface MenuItems {
  base_price: number | null;
  description: string | null;
  display_order: number;
  display_price: number | null;
  display_text: string | null;
  image_link: string | null;
  is_active: number;
  is_available: number;
  is_featured: Generated<number>;
  item_id: Generated<number>;
  name: string;
}

export interface ModifierOptions {
  base_price: number | null;
  display_text: string;
  is_active: number;
  is_available: number;
  modifier_id: number;
  name: string;
  option_id: Generated<number>;
  selection_option_id: number | null;
}

export interface Modifiers {
  default_option_id: number | null;
  description: string | null;
  display_order: number;
  display_text: string;
  is_active: number;
  is_available: number;
  is_required: number;
  max_selection: number | null;
  modifier_id: Generated<number>;
  modifier_type: "CHECKBOX" | "RADIO" | null;
  name: string;
}

export interface OptionOptionPrices {
  combo_id: Generated<number>;
  dependent_option_id: number;
  is_active: number;
  is_available: number;
  parent_option_id: number;
  price: number;
}

export interface OrderItemModifiers {
  modifier_option_id: number;
  order_item_id: number;
  order_item_modifier_id: Generated<number>;
  selection_option_id: number | null;
}

export interface OrderItems {
  item_id: number;
  item_price: number;
  order_id: number;
  order_item_id: Generated<number>;
}

export interface Orders {
  checkout_time: Date;
  delivery_method: "Delivery" | "Pickup";
  instructions: string | null;
  order_id: Generated<number>;
  status: string;
  total_price: number;
  user_id: number;
}

export interface SectionItems {
  combo_id: Generated<number>;
  display_order: number;
  is_active: number;
  is_available: number;
  item_id: number;
  section_id: number;
}

export interface Sections {
  display_order: number;
  display_text: string;
  is_active: number;
  is_available: number;
  name: string;
  section_id: Generated<number>;
}

export interface SelectionOptions {
  option_name: string;
  selection_option_id: Generated<number>;
}

export interface Users {
  email: string;
  first_name: string;
  last_login: Date | null;
  last_name: string;
  password_hash: string | null;
  phone_number: string;
  profile_picture: string | null;
  provider: string | null;
  registered_at: Date | null;
  user_id: Generated<number>;
}

export interface DB {
  addresses: Addresses;
  item_modifiers: ItemModifiers;
  item_option_prices: ItemOptionPrices;
  menu_items: MenuItems;
  modifier_options: ModifierOptions;
  modifiers: Modifiers;
  option_option_prices: OptionOptionPrices;
  order_item_modifiers: OrderItemModifiers;
  order_items: OrderItems;
  orders: Orders;
  section_items: SectionItems;
  sections: Sections;
  selection_options: SelectionOptions;
  users: Users;
}
